### ISSUE TITLE
remember line div[id=mark] is not working in Textual 5

### ISSUE THREAD

**Issue by DominusExult** [yyyc514/textual_bonfire_style#5]
Thanks for making bonfire style working with Textual 5.

There is one problem with the "remember" line, the mark, which is not showing at all.
If you change your "div#mark" to "div[id=mark]" and then comment in display.css 
line 48 div[id=mark] { display:table-row; }
line 75 div[id=mark] div { border-bottom: 2px dotted #c33; }
 and copy that "border-bottom: 2px dotted #c33;" to the div[id=mark] function in line 65 you can see the red marker again.

The only problem I noticed is that in one channel the table after the mark gets shifted to the left a bit, meaning the nickname and the message get moved to the left.

**Comment by yyyc514** [comment]
I just pushed a fix for this.
